services:
    search:
        image: elasticsearch:8.16.1
        environment:
            - cluster.name=es1
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ports:
            - 9200:9200
            - 9300:9300
    kibana:
        image: kibana:8.16.1
        environment:
            - ELASTICSEARCH_HOSTS=http://search:9200
            - ELASTIC_APM_SERVER_URL=http://telemetry:8200
        ports:
            - 5601:5601
    telemetry:
        image: elastic/apm-server:7.17.25
        command: apm-server -e -E output.elasticsearch.hosts=http://search:9200
        ports:
            - 8200:8200
