---
name: Execution Check Pinpoint-java
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        java:
          - 11
          - 17
          - 21
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }} OS ${{ matrix.os }} sample
    timeout-minutes: 30 # For check of functional runnability (currently 30 minutes, since pinpoint requires some server starts...)
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Run minimal parameter experiment and check success
        run: |
          ./setup.sh
          cd frameworks/pinpoint-java/ 
          export SLEEP_TIME=0
          export NUM_OF_LOOPS=1 
          export TOTAL_NUM_OF_CALLS=10 
          export RECURSION_DEPTH=10 
          ./benchmark.sh 
          unzip results-pinpoint-java/results.zip 
          measuredValues=$(cat raw-1-10-* | wc -l) 
          if [ $measuredValues -ne 50 ] 
          then
            echo "It should be 50 measured values, but was $measuredValues"
            exit 1
          fi

